### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cnlohr/cnfa#2]
I would like to point out that an identifier like “[`_CNFA_H`](https://github.com/cnlohr/cnfa/blob/22f0e58a4df57c6a6b5fa05665a6d454e597e2da/CNFA.h#L13 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by cnlohr** [comment]
I decline this.  I've thought about it for a while, but, I very much do not like the style of avoiding the prefix.

**Comment by elfring** [comment]
I would appreciate if [known risks according to undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?") will be avoided also for this software.
