### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [cnlohr/cnfa#3]
[Extra null pointer checks are not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [CloseCNFAAlsa](https://github.com/cnlohr/cnfa/blob/22f0e58a4df57c6a6b5fa05665a6d454e597e2da/CNFA_alsa.c#L49 "CloseCNFAAlsa function")
- [CloseCNFAPulse](https://github.com/cnlohr/cnfa/blob/22f0e58a4df57c6a6b5fa05665a6d454e597e2da/CNFA_pulse.c#L75 "CloseCNFAPulse function")

**Comment by cnlohr** [comment]
After a long discussion, because these are very rarely set, the `if` is there as an indicator to future programmers that these values will very commonly be null.  No change willbe made.  Thank you for pointing it out, though.

**Comment by elfring** [comment]
I would prefer source code with less questionable checks.
